title: Yannis (Ioannis) Panaretos
description: Student — Mathematics, Physics & Computer Science · Corfu, Greece
theme: jekyll-theme-minimal
logo: /yannis.jpg
show_downloads: false
google_analytics:
plugins:
  - jekyll-seo-tag
